[build]
  publish = "static"
  command = "node generate-posts.js"

[[redirects]]
  from = "/posts/*"
  to = "/post.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    
[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200
